/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package textanalyzer;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author andy
 */
public class TextFrame extends javax.swing.JPanel {

    /**
     * Creates new form TextFrame
     */
    public TextFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        textLength3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBoard = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textLength = new javax.swing.JLabel();
        noTabs = new javax.swing.JLabel();
        noWords = new javax.swing.JLabel();
        noSpace = new javax.swing.JLabel();
        noLines = new javax.swing.JLabel();
        length = new javax.swing.JTextField();
        lines = new javax.swing.JTextField();
        tabs = new javax.swing.JTextField();
        words = new javax.swing.JTextField();
        spaces = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        unique = new javax.swing.JComboBox<>();
        wordCount = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        ans = new javax.swing.JTextField();

        jLabel3.setText("jLabel2");

        textLength3.setBackground(new java.awt.Color(102, 102, 102));
        textLength3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        textLength3.setForeground(new java.awt.Color(255, 255, 255));
        textLength3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLength3.setText("Text Length : ");
        textLength3.setOpaque(true);

        jTextField1.setText("jTextField1");

        Title.setBackground(new java.awt.Color(255, 51, 51));
        Title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Text Analyzer");
        Title.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 204), new java.awt.Color(255, 102, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 0, 51)));

        textBoard.setColumns(20);
        textBoard.setLineWrap(true);
        textBoard.setRows(5);
        textBoard.setAlignmentX(10.0F);
        jScrollPane1.setViewportView(textBoard);

        Submit.setBackground(new java.awt.Color(153, 153, 255));
        Submit.setText("Submit");
        Submit.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textLength.setBackground(new java.awt.Color(102, 102, 102));
        textLength.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        textLength.setForeground(new java.awt.Color(255, 255, 255));
        textLength.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLength.setText("Text Length : ");
        textLength.setOpaque(true);

        noTabs.setBackground(new java.awt.Color(102, 102, 102));
        noTabs.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        noTabs.setForeground(new java.awt.Color(255, 255, 255));
        noTabs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTabs.setText("No of Tabs :");
        noTabs.setOpaque(true);

        noWords.setBackground(new java.awt.Color(102, 102, 102));
        noWords.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        noWords.setForeground(new java.awt.Color(255, 255, 255));
        noWords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noWords.setText("No of Words : ");
        noWords.setOpaque(true);

        noSpace.setBackground(new java.awt.Color(102, 102, 102));
        noSpace.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        noSpace.setForeground(new java.awt.Color(255, 255, 255));
        noSpace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noSpace.setText("No of Spaces :");
        noSpace.setOpaque(true);

        noLines.setBackground(new java.awt.Color(102, 102, 102));
        noLines.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        noLines.setForeground(new java.awt.Color(255, 255, 255));
        noLines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noLines.setText("No of Lines : ");
        noLines.setOpaque(true);

        length.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        length.setAlignmentX(5.0F);
        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        lines.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linesActionPerformed(evt);
            }
        });

        tabs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabsActionPerformed(evt);
            }
        });

        words.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        words.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsActionPerformed(evt);
            }
        });

        spaces.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spacesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textLength, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spaces, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(noLines, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lines, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLength, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noWords, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaces, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noLines, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lines, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        unique.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        unique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniqueActionPerformed(evt);
            }
        });

        wordCount.setText("Enter a word or Char");
        wordCount.setOpaque(true);
        wordCount.setPreferredSize(new java.awt.Dimension(10, 18));

        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        ans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ans, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(wordCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unique, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordCount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void getLength(String inputText){
        tLength = inputText.length();
        length.setText(tLength+"");
        tLength = 0;
    }
    
    public void getWords(String inputText){
        twords = inputText.trim().split("[\s]+").length;
        words.setText(twords+"");
        twords = 0;
    }
    
     public void getSpaces(String inputText){
        for(int i = 0;i < inputText.length();i++){
            if(inputText.charAt(i) == ' ') tspaces++;
        }
        //tspaces = inputText.split("[\s]").length - 1;
        spaces.setText(tspaces+"");
        tspaces = 0;
    }
    
    public void getTabs(String inputText){
        textBoard.setFocusTraversalKeysEnabled(false);
        for(int i = 0;i < inputText.length();i++){
            if(inputText.charAt(i) == '\t') ttabs++;
        }
        //ttabs = inputText.split("[\t]").length - 1;
        tabs.setText(ttabs+"");
        ttabs = 0;
    }
    
    public void getLines(String inputText){
        textBoard.setLineWrap(true);
        textBoard.setWrapStyleWord(true);
        tlines = textBoard.getLineCount();
        lines.setText(tlines+"");
        tlines = 0;
    }
    
    public void getWordOrCharCount(String input){
        String[] sp = inputText.splitWithDelimiters(input, inputText.length());
        for(String item : sp){
            if(item.equals(input)) twordCount++;
        }
        ans.setText("Count: "+twordCount);
        twordCount = 0;
    }
    
    public void getUniqueChar(String inputText){
        java.util.List <Character> uniqueChar = new java.util.ArrayList<>();
        char dummy;
        for(int i=0;i<inputText.length();i++){
            dummy = inputText.charAt(i);
            if(!uniqueChar.contains(dummy)) uniqueChar.add(dummy);
        }
        
        for (Character ch : uniqueChar) {
        model.addElement(String.valueOf(ch));
        }
        
           unique.setModel(model);
    }
  
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        inputText = textBoard.getText();
        
        getLength(inputText);
        getWords(inputText);
        getSpaces(inputText);
        getTabs(inputText);
        getLines(inputText);
        getUniqueChar(inputText);
        if(input.getText().length() > 0) getWordOrCharCount(input.getText());

    }//GEN-LAST:event_SubmitActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed

    }//GEN-LAST:event_lengthActionPerformed

    private void linesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linesActionPerformed

    private void tabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabsActionPerformed

    private void wordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordsActionPerformed

    private void spacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spacesActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansActionPerformed

    private void uniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniqueActionPerformed

    }//GEN-LAST:event_uniqueActionPerformed

    public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
        TextFrame panel = new TextFrame();
        JFrame frame = new JFrame("Text Analyzer");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(new TextFrame()); // Add your panel
        frame.pack(); // Adjust to fit preferred sizes
        frame.setLocationRelativeTo(null); // Center the window
        frame.setVisible(true); // Show the frame
        });
}

    private String inputText = "";
    private int tLength;
    private int twords;
    private int tspaces;
    private int ttabs;
    private int tlines;
    private int twordCount;
    javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField ans;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField length;
    private javax.swing.JTextField lines;
    private javax.swing.JLabel noLines;
    private javax.swing.JLabel noSpace;
    private javax.swing.JLabel noTabs;
    private javax.swing.JLabel noWords;
    private javax.swing.JTextField spaces;
    private javax.swing.JTextField tabs;
    private javax.swing.JTextArea textBoard;
    private javax.swing.JLabel textLength;
    private javax.swing.JLabel textLength3;
    private javax.swing.JComboBox<String> unique;
    private javax.swing.JLabel wordCount;
    private javax.swing.JTextField words;
    // End of variables declaration//GEN-END:variables
}
