/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    

    public static void main(String[] args) {
        App E = new App();
        Animals tiger = new Animals((byte)25,"Wild","Male","Other animals");
        Plants mango = new Plants((byte)40,"domestic","Fruit","mid");
        
        System.out.println(tiger);
        System.out.println(mango);
        
    }
}
